[package]
name = "talk-server"
version = "0.1.0"
edition = "2021"

[dependencies]
bytes = "1.6.0"
chrono = "0.4.38"
rusqlite = "0.31.0"
serde = "1.0.202"
serde_derive = "1.0.202"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1.15"
uuid = "1.8.0"
